/*
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.upb.lp.isc.LosMelosRuntimeModule;
import edu.upb.lp.isc.LosMelosStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LosMelosIdeSetup extends LosMelosStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LosMelosRuntimeModule(), new LosMelosIdeModule()));
	}
	
}
