/*
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.parser.antlr;

import com.google.inject.Inject;
import edu.upb.lp.isc.parser.antlr.internal.InternalLosMelosParser;
import edu.upb.lp.isc.services.LosMelosGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LosMelosParser extends AbstractAntlrParser {

	@Inject
	private LosMelosGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLosMelosParser createParser(XtextTokenStream stream) {
		return new InternalLosMelosParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public LosMelosGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LosMelosGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
