/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.generator;

import edu.upb.lp.isc.losMelos.Program;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class LosMelosGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _head = IteratorExtensions.<EObject>head(resource.getAllContents());
    final Program b = ((Program) _head);
    String _name = b.getName();
    String _plus = (_name + ".py");
    fsa.generateFile(_plus, this.generatePython(b));
  }
  
  public CharSequence generatePython(final Program p) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("digraph {");
    _builder.newLine();
    _builder.append("       ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    return _builder;
  }
}
