/*
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.ui;

import com.google.inject.Injector;
import losMelos.ui.internal.LosMelosActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LosMelosExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LosMelosActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LosMelosActivator activator = LosMelosActivator.getInstance();
		return activator != null ? activator.getInjector(LosMelosActivator.EDU_UPB_LP_ISC_LOSMELOS) : null;
	}

}
