/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos.impl;

import edu.upb.lp.isc.losMelos.Ejecuciones;
import edu.upb.lp.isc.losMelos.LosMelosPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ejecuciones</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EjecucionesImpl extends MinimalEObjectImpl.Container implements Ejecuciones
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EjecucionesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LosMelosPackage.Literals.EJECUCIONES;
  }

} //EjecucionesImpl
