/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos.impl;

import edu.upb.lp.isc.losMelos.ExprCons;
import edu.upb.lp.isc.losMelos.Expresion;
import edu.upb.lp.isc.losMelos.LosMelosPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expr Cons</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losMelos.impl.ExprConsImpl#getL1 <em>L1</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losMelos.impl.ExprConsImpl#getL2 <em>L2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExprConsImpl extends FuncListImpl implements ExprCons
{
  /**
   * The cached value of the '{@link #getL1() <em>L1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getL1()
   * @generated
   * @ordered
   */
  protected Expresion l1;

  /**
   * The cached value of the '{@link #getL2() <em>L2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getL2()
   * @generated
   * @ordered
   */
  protected Expresion l2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExprConsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LosMelosPackage.Literals.EXPR_CONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expresion getL1()
  {
    return l1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetL1(Expresion newL1, NotificationChain msgs)
  {
    Expresion oldL1 = l1;
    l1 = newL1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LosMelosPackage.EXPR_CONS__L1, oldL1, newL1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setL1(Expresion newL1)
  {
    if (newL1 != l1)
    {
      NotificationChain msgs = null;
      if (l1 != null)
        msgs = ((InternalEObject)l1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LosMelosPackage.EXPR_CONS__L1, null, msgs);
      if (newL1 != null)
        msgs = ((InternalEObject)newL1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LosMelosPackage.EXPR_CONS__L1, null, msgs);
      msgs = basicSetL1(newL1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LosMelosPackage.EXPR_CONS__L1, newL1, newL1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expresion getL2()
  {
    return l2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetL2(Expresion newL2, NotificationChain msgs)
  {
    Expresion oldL2 = l2;
    l2 = newL2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LosMelosPackage.EXPR_CONS__L2, oldL2, newL2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setL2(Expresion newL2)
  {
    if (newL2 != l2)
    {
      NotificationChain msgs = null;
      if (l2 != null)
        msgs = ((InternalEObject)l2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LosMelosPackage.EXPR_CONS__L2, null, msgs);
      if (newL2 != null)
        msgs = ((InternalEObject)newL2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LosMelosPackage.EXPR_CONS__L2, null, msgs);
      msgs = basicSetL2(newL2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LosMelosPackage.EXPR_CONS__L2, newL2, newL2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LosMelosPackage.EXPR_CONS__L1:
        return basicSetL1(null, msgs);
      case LosMelosPackage.EXPR_CONS__L2:
        return basicSetL2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LosMelosPackage.EXPR_CONS__L1:
        return getL1();
      case LosMelosPackage.EXPR_CONS__L2:
        return getL2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LosMelosPackage.EXPR_CONS__L1:
        setL1((Expresion)newValue);
        return;
      case LosMelosPackage.EXPR_CONS__L2:
        setL2((Expresion)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LosMelosPackage.EXPR_CONS__L1:
        setL1((Expresion)null);
        return;
      case LosMelosPackage.EXPR_CONS__L2:
        setL2((Expresion)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LosMelosPackage.EXPR_CONS__L1:
        return l1 != null;
      case LosMelosPackage.EXPR_CONS__L2:
        return l2 != null;
    }
    return super.eIsSet(featureID);
  }

} //ExprConsImpl
