/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos.impl;

import edu.upb.lp.isc.losMelos.ExprArithmetic;
import edu.upb.lp.isc.losMelos.Expresion;
import edu.upb.lp.isc.losMelos.LosMelosPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expr Arithmetic</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losMelos.impl.ExprArithmeticImpl#getSimbolo <em>Simbolo</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losMelos.impl.ExprArithmeticImpl#getVal1 <em>Val1</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losMelos.impl.ExprArithmeticImpl#getVal2 <em>Val2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExprArithmeticImpl extends ExprNumberImpl implements ExprArithmetic
{
  /**
   * The default value of the '{@link #getSimbolo() <em>Simbolo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSimbolo()
   * @generated
   * @ordered
   */
  protected static final String SIMBOLO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSimbolo() <em>Simbolo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSimbolo()
   * @generated
   * @ordered
   */
  protected String simbolo = SIMBOLO_EDEFAULT;

  /**
   * The cached value of the '{@link #getVal1() <em>Val1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVal1()
   * @generated
   * @ordered
   */
  protected Expresion val1;

  /**
   * The cached value of the '{@link #getVal2() <em>Val2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVal2()
   * @generated
   * @ordered
   */
  protected Expresion val2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExprArithmeticImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LosMelosPackage.Literals.EXPR_ARITHMETIC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSimbolo()
  {
    return simbolo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSimbolo(String newSimbolo)
  {
    String oldSimbolo = simbolo;
    simbolo = newSimbolo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LosMelosPackage.EXPR_ARITHMETIC__SIMBOLO, oldSimbolo, simbolo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expresion getVal1()
  {
    return val1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVal1(Expresion newVal1, NotificationChain msgs)
  {
    Expresion oldVal1 = val1;
    val1 = newVal1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LosMelosPackage.EXPR_ARITHMETIC__VAL1, oldVal1, newVal1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVal1(Expresion newVal1)
  {
    if (newVal1 != val1)
    {
      NotificationChain msgs = null;
      if (val1 != null)
        msgs = ((InternalEObject)val1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LosMelosPackage.EXPR_ARITHMETIC__VAL1, null, msgs);
      if (newVal1 != null)
        msgs = ((InternalEObject)newVal1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LosMelosPackage.EXPR_ARITHMETIC__VAL1, null, msgs);
      msgs = basicSetVal1(newVal1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LosMelosPackage.EXPR_ARITHMETIC__VAL1, newVal1, newVal1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expresion getVal2()
  {
    return val2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVal2(Expresion newVal2, NotificationChain msgs)
  {
    Expresion oldVal2 = val2;
    val2 = newVal2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LosMelosPackage.EXPR_ARITHMETIC__VAL2, oldVal2, newVal2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVal2(Expresion newVal2)
  {
    if (newVal2 != val2)
    {
      NotificationChain msgs = null;
      if (val2 != null)
        msgs = ((InternalEObject)val2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LosMelosPackage.EXPR_ARITHMETIC__VAL2, null, msgs);
      if (newVal2 != null)
        msgs = ((InternalEObject)newVal2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LosMelosPackage.EXPR_ARITHMETIC__VAL2, null, msgs);
      msgs = basicSetVal2(newVal2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LosMelosPackage.EXPR_ARITHMETIC__VAL2, newVal2, newVal2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LosMelosPackage.EXPR_ARITHMETIC__VAL1:
        return basicSetVal1(null, msgs);
      case LosMelosPackage.EXPR_ARITHMETIC__VAL2:
        return basicSetVal2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LosMelosPackage.EXPR_ARITHMETIC__SIMBOLO:
        return getSimbolo();
      case LosMelosPackage.EXPR_ARITHMETIC__VAL1:
        return getVal1();
      case LosMelosPackage.EXPR_ARITHMETIC__VAL2:
        return getVal2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LosMelosPackage.EXPR_ARITHMETIC__SIMBOLO:
        setSimbolo((String)newValue);
        return;
      case LosMelosPackage.EXPR_ARITHMETIC__VAL1:
        setVal1((Expresion)newValue);
        return;
      case LosMelosPackage.EXPR_ARITHMETIC__VAL2:
        setVal2((Expresion)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LosMelosPackage.EXPR_ARITHMETIC__SIMBOLO:
        setSimbolo(SIMBOLO_EDEFAULT);
        return;
      case LosMelosPackage.EXPR_ARITHMETIC__VAL1:
        setVal1((Expresion)null);
        return;
      case LosMelosPackage.EXPR_ARITHMETIC__VAL2:
        setVal2((Expresion)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LosMelosPackage.EXPR_ARITHMETIC__SIMBOLO:
        return SIMBOLO_EDEFAULT == null ? simbolo != null : !SIMBOLO_EDEFAULT.equals(simbolo);
      case LosMelosPackage.EXPR_ARITHMETIC__VAL1:
        return val1 != null;
      case LosMelosPackage.EXPR_ARITHMETIC__VAL2:
        return val2 != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (simbolo: ");
    result.append(simbolo);
    result.append(')');
    return result.toString();
  }

} //ExprArithmeticImpl
