/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos.impl;

import edu.upb.lp.isc.losMelos.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class LosMelosFactoryImpl extends EFactoryImpl implements LosMelosFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static LosMelosFactory init()
  {
    try
    {
      LosMelosFactory theLosMelosFactory = (LosMelosFactory)EPackage.Registry.INSTANCE.getEFactory(LosMelosPackage.eNS_URI);
      if (theLosMelosFactory != null)
      {
        return theLosMelosFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new LosMelosFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LosMelosFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case LosMelosPackage.PROGRAM: return createProgram();
      case LosMelosPackage.DEFINICIONES: return createDefiniciones();
      case LosMelosPackage.FUNCIONES: return createFunciones();
      case LosMelosPackage.VARIABLES: return createVariables();
      case LosMelosPackage.EXPRESION: return createExpresion();
      case LosMelosPackage.LLAMADA_PARAMETRO: return createLlamadaParametro();
      case LosMelosPackage.EXPRESION_VAR: return createExpresionVar();
      case LosMelosPackage.BASICA: return createBasica();
      case LosMelosPackage.EXPR_STRING: return createExprString();
      case LosMelosPackage.EXPR_NUMBER: return createExprNumber();
      case LosMelosPackage.EXPR_INT: return createExprInt();
      case LosMelosPackage.EXPR_ARITHMETIC: return createExprArithmetic();
      case LosMelosPackage.EXPR_PARAM: return createExprParam();
      case LosMelosPackage.LLAMADA_FUNCION: return createLlamadaFuncion();
      case LosMelosPackage.EXPR_BOOL: return createExprBool();
      case LosMelosPackage.VAL_BOOL: return createValBool();
      case LosMelosPackage.COMP_BOOL: return createCompBool();
      case LosMelosPackage.OP_BOOL: return createOpBool();
      case LosMelosPackage.EXPR_IF: return createExprIf();
      case LosMelosPackage.EXPR_THEN: return createExprThen();
      case LosMelosPackage.EXPR_ELSE: return createExprElse();
      case LosMelosPackage.EXPR_LIST: return createExprList();
      case LosMelosPackage.EXPR_LIST2: return createExprList2();
      case LosMelosPackage.ELEMENT_LIST: return createElementList();
      case LosMelosPackage.FUNC_LIST: return createFuncList();
      case LosMelosPackage.EXPR_CAR: return createExprCar();
      case LosMelosPackage.EXPR_CDR: return createExprCdr();
      case LosMelosPackage.EXPR_CONS: return createExprCons();
      case LosMelosPackage.EXPR_IS_EMPTY: return createExprIsEmpty();
      case LosMelosPackage.EXPR_LENGTH: return createExprLength();
      case LosMelosPackage.EXPR_PRINT: return createExprPrint();
      case LosMelosPackage.EJECUCIONES: return createEjecuciones();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Program createProgram()
  {
    ProgramImpl program = new ProgramImpl();
    return program;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Definiciones createDefiniciones()
  {
    DefinicionesImpl definiciones = new DefinicionesImpl();
    return definiciones;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Funciones createFunciones()
  {
    FuncionesImpl funciones = new FuncionesImpl();
    return funciones;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Variables createVariables()
  {
    VariablesImpl variables = new VariablesImpl();
    return variables;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expresion createExpresion()
  {
    ExpresionImpl expresion = new ExpresionImpl();
    return expresion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LlamadaParametro createLlamadaParametro()
  {
    LlamadaParametroImpl llamadaParametro = new LlamadaParametroImpl();
    return llamadaParametro;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExpresionVar createExpresionVar()
  {
    ExpresionVarImpl expresionVar = new ExpresionVarImpl();
    return expresionVar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Basica createBasica()
  {
    BasicaImpl basica = new BasicaImpl();
    return basica;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprString createExprString()
  {
    ExprStringImpl exprString = new ExprStringImpl();
    return exprString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprNumber createExprNumber()
  {
    ExprNumberImpl exprNumber = new ExprNumberImpl();
    return exprNumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprInt createExprInt()
  {
    ExprIntImpl exprInt = new ExprIntImpl();
    return exprInt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprArithmetic createExprArithmetic()
  {
    ExprArithmeticImpl exprArithmetic = new ExprArithmeticImpl();
    return exprArithmetic;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprParam createExprParam()
  {
    ExprParamImpl exprParam = new ExprParamImpl();
    return exprParam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LlamadaFuncion createLlamadaFuncion()
  {
    LlamadaFuncionImpl llamadaFuncion = new LlamadaFuncionImpl();
    return llamadaFuncion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprBool createExprBool()
  {
    ExprBoolImpl exprBool = new ExprBoolImpl();
    return exprBool;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ValBool createValBool()
  {
    ValBoolImpl valBool = new ValBoolImpl();
    return valBool;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CompBool createCompBool()
  {
    CompBoolImpl compBool = new CompBoolImpl();
    return compBool;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OpBool createOpBool()
  {
    OpBoolImpl opBool = new OpBoolImpl();
    return opBool;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprIf createExprIf()
  {
    ExprIfImpl exprIf = new ExprIfImpl();
    return exprIf;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprThen createExprThen()
  {
    ExprThenImpl exprThen = new ExprThenImpl();
    return exprThen;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprElse createExprElse()
  {
    ExprElseImpl exprElse = new ExprElseImpl();
    return exprElse;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprList createExprList()
  {
    ExprListImpl exprList = new ExprListImpl();
    return exprList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprList2 createExprList2()
  {
    ExprList2Impl exprList2 = new ExprList2Impl();
    return exprList2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ElementList createElementList()
  {
    ElementListImpl elementList = new ElementListImpl();
    return elementList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FuncList createFuncList()
  {
    FuncListImpl funcList = new FuncListImpl();
    return funcList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprCar createExprCar()
  {
    ExprCarImpl exprCar = new ExprCarImpl();
    return exprCar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprCdr createExprCdr()
  {
    ExprCdrImpl exprCdr = new ExprCdrImpl();
    return exprCdr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprCons createExprCons()
  {
    ExprConsImpl exprCons = new ExprConsImpl();
    return exprCons;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprIsEmpty createExprIsEmpty()
  {
    ExprIsEmptyImpl exprIsEmpty = new ExprIsEmptyImpl();
    return exprIsEmpty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprLength createExprLength()
  {
    ExprLengthImpl exprLength = new ExprLengthImpl();
    return exprLength;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprPrint createExprPrint()
  {
    ExprPrintImpl exprPrint = new ExprPrintImpl();
    return exprPrint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ejecuciones createEjecuciones()
  {
    EjecucionesImpl ejecuciones = new EjecucionesImpl();
    return ejecuciones;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LosMelosPackage getLosMelosPackage()
  {
    return (LosMelosPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static LosMelosPackage getPackage()
  {
    return LosMelosPackage.eINSTANCE;
  }

} //LosMelosFactoryImpl
