/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos.impl;

import edu.upb.lp.isc.losMelos.Definiciones;
import edu.upb.lp.isc.losMelos.Ejecuciones;
import edu.upb.lp.isc.losMelos.LosMelosPackage;
import edu.upb.lp.isc.losMelos.Program;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losMelos.impl.ProgramImpl#getName <em>Name</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losMelos.impl.ProgramImpl#getSeccionDefiniciones <em>Seccion Definiciones</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losMelos.impl.ProgramImpl#getSeccionEjecuciones <em>Seccion Ejecuciones</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProgramImpl extends MinimalEObjectImpl.Container implements Program
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getSeccionDefiniciones() <em>Seccion Definiciones</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeccionDefiniciones()
   * @generated
   * @ordered
   */
  protected EList<Definiciones> seccionDefiniciones;

  /**
   * The cached value of the '{@link #getSeccionEjecuciones() <em>Seccion Ejecuciones</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeccionEjecuciones()
   * @generated
   * @ordered
   */
  protected EList<Ejecuciones> seccionEjecuciones;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProgramImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LosMelosPackage.Literals.PROGRAM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LosMelosPackage.PROGRAM__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Definiciones> getSeccionDefiniciones()
  {
    if (seccionDefiniciones == null)
    {
      seccionDefiniciones = new EObjectContainmentEList<Definiciones>(Definiciones.class, this, LosMelosPackage.PROGRAM__SECCION_DEFINICIONES);
    }
    return seccionDefiniciones;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Ejecuciones> getSeccionEjecuciones()
  {
    if (seccionEjecuciones == null)
    {
      seccionEjecuciones = new EObjectContainmentEList<Ejecuciones>(Ejecuciones.class, this, LosMelosPackage.PROGRAM__SECCION_EJECUCIONES);
    }
    return seccionEjecuciones;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LosMelosPackage.PROGRAM__SECCION_DEFINICIONES:
        return ((InternalEList<?>)getSeccionDefiniciones()).basicRemove(otherEnd, msgs);
      case LosMelosPackage.PROGRAM__SECCION_EJECUCIONES:
        return ((InternalEList<?>)getSeccionEjecuciones()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LosMelosPackage.PROGRAM__NAME:
        return getName();
      case LosMelosPackage.PROGRAM__SECCION_DEFINICIONES:
        return getSeccionDefiniciones();
      case LosMelosPackage.PROGRAM__SECCION_EJECUCIONES:
        return getSeccionEjecuciones();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LosMelosPackage.PROGRAM__NAME:
        setName((String)newValue);
        return;
      case LosMelosPackage.PROGRAM__SECCION_DEFINICIONES:
        getSeccionDefiniciones().clear();
        getSeccionDefiniciones().addAll((Collection<? extends Definiciones>)newValue);
        return;
      case LosMelosPackage.PROGRAM__SECCION_EJECUCIONES:
        getSeccionEjecuciones().clear();
        getSeccionEjecuciones().addAll((Collection<? extends Ejecuciones>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LosMelosPackage.PROGRAM__NAME:
        setName(NAME_EDEFAULT);
        return;
      case LosMelosPackage.PROGRAM__SECCION_DEFINICIONES:
        getSeccionDefiniciones().clear();
        return;
      case LosMelosPackage.PROGRAM__SECCION_EJECUCIONES:
        getSeccionEjecuciones().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LosMelosPackage.PROGRAM__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case LosMelosPackage.PROGRAM__SECCION_DEFINICIONES:
        return seccionDefiniciones != null && !seccionDefiniciones.isEmpty();
      case LosMelosPackage.PROGRAM__SECCION_EJECUCIONES:
        return seccionEjecuciones != null && !seccionEjecuciones.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ProgramImpl
