/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos.impl;

import edu.upb.lp.isc.losMelos.LosMelosPackage;
import edu.upb.lp.isc.losMelos.ValBool;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Val Bool</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ValBoolImpl extends ExprBoolImpl implements ValBool
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ValBoolImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LosMelosPackage.Literals.VAL_BOOL;
  }

} //ValBoolImpl
