/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comp Bool</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losMelos.CompBool#getVal3 <em>Val3</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losMelos.CompBool#getVal4 <em>Val4</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getCompBool()
 * @model
 * @generated
 */
public interface CompBool extends ExprBool
{
  /**
   * Returns the value of the '<em><b>Val3</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val3</em>' containment reference.
   * @see #setVal3(Expresion)
   * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getCompBool_Val3()
   * @model containment="true"
   * @generated
   */
  Expresion getVal3();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losMelos.CompBool#getVal3 <em>Val3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val3</em>' containment reference.
   * @see #getVal3()
   * @generated
   */
  void setVal3(Expresion value);

  /**
   * Returns the value of the '<em><b>Val4</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val4</em>' containment reference.
   * @see #setVal4(Expresion)
   * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getCompBool_Val4()
   * @model containment="true"
   * @generated
   */
  Expresion getVal4();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losMelos.CompBool#getVal4 <em>Val4</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val4</em>' containment reference.
   * @see #getVal4()
   * @generated
   */
  void setVal4(Expresion value);

} // CompBool
