/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Cons</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losMelos.ExprCons#getL1 <em>L1</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losMelos.ExprCons#getL2 <em>L2</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getExprCons()
 * @model
 * @generated
 */
public interface ExprCons extends FuncList
{
  /**
   * Returns the value of the '<em><b>L1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>L1</em>' containment reference.
   * @see #setL1(Expresion)
   * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getExprCons_L1()
   * @model containment="true"
   * @generated
   */
  Expresion getL1();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losMelos.ExprCons#getL1 <em>L1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>L1</em>' containment reference.
   * @see #getL1()
   * @generated
   */
  void setL1(Expresion value);

  /**
   * Returns the value of the '<em><b>L2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>L2</em>' containment reference.
   * @see #setL2(Expresion)
   * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getExprCons_L2()
   * @model containment="true"
   * @generated
   */
  Expresion getL2();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losMelos.ExprCons#getL2 <em>L2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>L2</em>' containment reference.
   * @see #getL2()
   * @generated
   */
  void setL2(Expresion value);

} // ExprCons
