/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Number</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getExprNumber()
 * @model
 * @generated
 */
public interface ExprNumber extends Basica
{
} // ExprNumber
