/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Is Empty</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losMelos.ExprIsEmpty#getList <em>List</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getExprIsEmpty()
 * @model
 * @generated
 */
public interface ExprIsEmpty extends FuncList
{
  /**
   * Returns the value of the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' containment reference.
   * @see #setList(Expresion)
   * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getExprIsEmpty_List()
   * @model containment="true"
   * @generated
   */
  Expresion getList();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losMelos.ExprIsEmpty#getList <em>List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' containment reference.
   * @see #getList()
   * @generated
   */
  void setList(Expresion value);

} // ExprIsEmpty
