/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr If</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losMelos.ExprIf#getCondition <em>Condition</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losMelos.ExprIf#getThen <em>Then</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losMelos.ExprIf#getElse <em>Else</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getExprIf()
 * @model
 * @generated
 */
public interface ExprIf extends Expresion, Ejecuciones
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(EObject)
   * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getExprIf_Condition()
   * @model containment="true"
   * @generated
   */
  EObject getCondition();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losMelos.ExprIf#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(EObject value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference.
   * @see #setThen(ExprThen)
   * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getExprIf_Then()
   * @model containment="true"
   * @generated
   */
  ExprThen getThen();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losMelos.ExprIf#getThen <em>Then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' containment reference.
   * @see #getThen()
   * @generated
   */
  void setThen(ExprThen value);

  /**
   * Returns the value of the '<em><b>Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else</em>' containment reference.
   * @see #setElse(ExprElse)
   * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getExprIf_Else()
   * @model containment="true"
   * @generated
   */
  ExprElse getElse();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losMelos.ExprIf#getElse <em>Else</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else</em>' containment reference.
   * @see #getElse()
   * @generated
   */
  void setElse(ExprElse value);

} // ExprIf
