/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr List2</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losMelos.ExprList2#getLista <em>Lista</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getExprList2()
 * @model
 * @generated
 */
public interface ExprList2 extends Expresion
{
  /**
   * Returns the value of the '<em><b>Lista</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.losMelos.Expresion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lista</em>' containment reference list.
   * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getExprList2_Lista()
   * @model containment="true"
   * @generated
   */
  EList<Expresion> getLista();

} // ExprList2
