/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Funciones</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losMelos.Funciones#getParam <em>Param</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losMelos.Funciones#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getFunciones()
 * @model
 * @generated
 */
public interface Funciones extends Definiciones
{
  /**
   * Returns the value of the '<em><b>Param</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' attribute list.
   * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getFunciones_Param()
   * @model unique="false"
   * @generated
   */
  EList<String> getParam();

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Expresion)
   * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getFunciones_Body()
   * @model containment="true"
   * @generated
   */
  Expresion getBody();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losMelos.Funciones#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Expresion value);

} // Funciones
