/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Llamada Parametro</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losMelos.LlamadaParametro#getParam <em>Param</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getLlamadaParametro()
 * @model
 * @generated
 */
public interface LlamadaParametro extends EObject
{
  /**
   * Returns the value of the '<em><b>Param</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' reference.
   * @see #setParam(ExprParam)
   * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getLlamadaParametro_Param()
   * @model
   * @generated
   */
  ExprParam getParam();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losMelos.LlamadaParametro#getParam <em>Param</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param</em>' reference.
   * @see #getParam()
   * @generated
   */
  void setParam(ExprParam value);

} // LlamadaParametro
