/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see edu.upb.lp.isc.losMelos.LosMelosPackage
 * @generated
 */
public interface LosMelosFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LosMelosFactory eINSTANCE = edu.upb.lp.isc.losMelos.impl.LosMelosFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Program</em>'.
   * @generated
   */
  Program createProgram();

  /**
   * Returns a new object of class '<em>Definiciones</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Definiciones</em>'.
   * @generated
   */
  Definiciones createDefiniciones();

  /**
   * Returns a new object of class '<em>Funciones</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Funciones</em>'.
   * @generated
   */
  Funciones createFunciones();

  /**
   * Returns a new object of class '<em>Variables</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variables</em>'.
   * @generated
   */
  Variables createVariables();

  /**
   * Returns a new object of class '<em>Expresion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion</em>'.
   * @generated
   */
  Expresion createExpresion();

  /**
   * Returns a new object of class '<em>Llamada Parametro</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Llamada Parametro</em>'.
   * @generated
   */
  LlamadaParametro createLlamadaParametro();

  /**
   * Returns a new object of class '<em>Expresion Var</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion Var</em>'.
   * @generated
   */
  ExpresionVar createExpresionVar();

  /**
   * Returns a new object of class '<em>Basica</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Basica</em>'.
   * @generated
   */
  Basica createBasica();

  /**
   * Returns a new object of class '<em>Expr String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr String</em>'.
   * @generated
   */
  ExprString createExprString();

  /**
   * Returns a new object of class '<em>Expr Number</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Number</em>'.
   * @generated
   */
  ExprNumber createExprNumber();

  /**
   * Returns a new object of class '<em>Expr Int</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Int</em>'.
   * @generated
   */
  ExprInt createExprInt();

  /**
   * Returns a new object of class '<em>Expr Arithmetic</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Arithmetic</em>'.
   * @generated
   */
  ExprArithmetic createExprArithmetic();

  /**
   * Returns a new object of class '<em>Expr Param</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Param</em>'.
   * @generated
   */
  ExprParam createExprParam();

  /**
   * Returns a new object of class '<em>Llamada Funcion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Llamada Funcion</em>'.
   * @generated
   */
  LlamadaFuncion createLlamadaFuncion();

  /**
   * Returns a new object of class '<em>Expr Bool</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Bool</em>'.
   * @generated
   */
  ExprBool createExprBool();

  /**
   * Returns a new object of class '<em>Val Bool</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Val Bool</em>'.
   * @generated
   */
  ValBool createValBool();

  /**
   * Returns a new object of class '<em>Comp Bool</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comp Bool</em>'.
   * @generated
   */
  CompBool createCompBool();

  /**
   * Returns a new object of class '<em>Op Bool</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Op Bool</em>'.
   * @generated
   */
  OpBool createOpBool();

  /**
   * Returns a new object of class '<em>Expr If</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr If</em>'.
   * @generated
   */
  ExprIf createExprIf();

  /**
   * Returns a new object of class '<em>Expr Then</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Then</em>'.
   * @generated
   */
  ExprThen createExprThen();

  /**
   * Returns a new object of class '<em>Expr Else</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Else</em>'.
   * @generated
   */
  ExprElse createExprElse();

  /**
   * Returns a new object of class '<em>Expr List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr List</em>'.
   * @generated
   */
  ExprList createExprList();

  /**
   * Returns a new object of class '<em>Expr List2</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr List2</em>'.
   * @generated
   */
  ExprList2 createExprList2();

  /**
   * Returns a new object of class '<em>Element List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element List</em>'.
   * @generated
   */
  ElementList createElementList();

  /**
   * Returns a new object of class '<em>Func List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func List</em>'.
   * @generated
   */
  FuncList createFuncList();

  /**
   * Returns a new object of class '<em>Expr Car</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Car</em>'.
   * @generated
   */
  ExprCar createExprCar();

  /**
   * Returns a new object of class '<em>Expr Cdr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Cdr</em>'.
   * @generated
   */
  ExprCdr createExprCdr();

  /**
   * Returns a new object of class '<em>Expr Cons</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Cons</em>'.
   * @generated
   */
  ExprCons createExprCons();

  /**
   * Returns a new object of class '<em>Expr Is Empty</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Is Empty</em>'.
   * @generated
   */
  ExprIsEmpty createExprIsEmpty();

  /**
   * Returns a new object of class '<em>Expr Length</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Length</em>'.
   * @generated
   */
  ExprLength createExprLength();

  /**
   * Returns a new object of class '<em>Expr Print</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Print</em>'.
   * @generated
   */
  ExprPrint createExprPrint();

  /**
   * Returns a new object of class '<em>Ejecuciones</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ejecuciones</em>'.
   * @generated
   */
  Ejecuciones createEjecuciones();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  LosMelosPackage getLosMelosPackage();

} //LosMelosFactory
