/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Val Bool</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getValBool()
 * @model
 * @generated
 */
public interface ValBool extends ExprBool
{
} // ValBool
