/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.losMelos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variables</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losMelos.Variables#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getVariables()
 * @model
 * @generated
 */
public interface Variables extends Definiciones
{
  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(ExpresionVar)
   * @see edu.upb.lp.isc.losMelos.LosMelosPackage#getVariables_Body()
   * @model containment="true"
   * @generated
   */
  ExpresionVar getBody();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losMelos.Variables#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(ExpresionVar value);

} // Variables
